version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: trip-reservation-system
    container_name: trip-reservation-system
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"